language: java
jdk: oraclejdk8
install: true
addons:
  sonarcloud:
    organization: jaisonpereira-github
    token:
      secure: of+Xa7fqtUzIRu/PuTEX2PZwp/rw8x3Y/yiFYMDfu4FjDZvCYs1x8Tz8oxV1U8CuleslX7BwD94f8VIcopex8nN26QBbOeVfEMMStZjaN7Ny0NDg2gR7dYN8S17cO/oAow5GmG5mstxBjbl+Uv7nVVZQIrVwo4z/x5Fy4mXa6zITAnixvTt28It7ZbcZ7vy22Ksazs9YXNNdg+2CdZDeAv0cHNgxCMFaXdNFEEz+Rm3j9OE+5KVcD/N4E7oxU5hNpkHgzN8UowxvcGkf4vCwJ/FV75OEM3tsJj9q8yzeAjT59ZsM8XYlY2CC+/3b7CF7k6BaL97WhP+iE/YVYqY7/ciRM7IoQx6kMW4GM+wgsb2AAfQGwrud2HzqohURNB3JJXy+/IzbJgXH8HD1s6xLb2x7cED0Z6Vp+dE8aG1btIQ4J4AG1ZJrOYGO6XDRmk9PKp7fQKKuhB0WvTM7WQpmbihhxTgV7ZhwtzXgtUxsFFrhQtKx5BJGqbpaVlZaKkYbpga4BIDQR7u6SaBQgUGxOxyU4PZCrT4j/cjC0ce9fVP9k8+gl6/KpP38m/5Q49L7vxZYEbA0o/5DOvja4twT5UcA7ovuQFFj1IbZqUwPvqZUSQ3d8P4kVxqyOsxB/hLUdiRAeKkYLPro9w0nrsjF370fP2kiDPV0ticvXCuWpkU=
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
branches:
  only:
  - master
  - test
  - dev
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar