language: java
jdk: oraclejdk8
install: true
addons:
  sonarcloud:
    organization: jaisonpereira-github
    token:
      secure: QbkNYN/2nsw+AQkxvl1GO+dVLtvX3dqu8fvP/3vU/LyyDYRfu6WtG9yK9mhcTWdQh5fyB+riZ78zFfM8Xz/y68wmhd4DkaIDl03yfgYXeecY1SP6RpIaIIBzvsqKdP0K9G+tda0jBmvfwE/HHAqzXbLa+GTDAWMOsDl2KTdjpsK4uxpGCI4OARuybY/zW/j+ytLuq+CMsvor5kgpKft2lnZBZkAEjOMDzFocazdgvUarBWvrotJzF+WpgVETvX5lO67QLafZvAr103gDIRwfE1/XeGmo8Saptq+96v6sEQ1osI55QVne9NBViqv+30czxypMgmjBbn+Akf43WbiLIClQEm1ckEFlIAmjt7NKsPKB6YEf+sFJSuBq4BDLZkEkr6A9aqv7pTy4ICE/T4Q1b3SMaHwkB2zfZYheSknNNyAt+QGoh1PjPJgj0U704e1jbfD3RQFbEKiDAaek83eRtL0oImSpWPfzvZanDJO0fNxDUrIFMBQmu0MBUrsRu4GmV4HLZp8eE37hi9qmepxCeePZ/DekG31eywhydFPNL8So+n6hSG5wyrjtKxZpyOBUWPwFjHsUtZEa90cCMYnexzjnPWm5b279SoTFu7koyv8xJ7kgacBYeEHxF4VIGUC4IFhdh0zWKgp6f0vd/f4G6cdRq9X1oECf4T1STBcKnKc="
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
branches:
  only:
  - master
  - test
  - dev
script:
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar