language: java
jdk: oraclejdk8
install: true
addons:
  sonarcloud:
    organization: jaisonpereira-github
    token:
      secure: bRkognZPl8aDCEjlc37Rr6fEHnKj5X2Yb+wm+BhFDsYo97DY/KVb4lF/9yIcsO/ftoXKo0+cIQ7HFEQWkxF9DY84wQOvlni4Sh4tm8eJW+o3RyPo6nxXmdfj2B7WuiFs2JtCOvydyfwSiRbw1SD2k2p1LNh0PS65q6TPsPElUg6KOnDWEQoQH92Tek8LBoJamhlwVopSFJUiVt2wn8a/vcQ4snsKGbSKocGYns5PqqTeBTI/Vw1CFTMknv+NAlO03ZsLouQMss5BTiOP1qTX5R8xFm3vxtub4LcV5hosh/ZMQMjZw0xLpL2eIJFvqppVXfO7jt7izxH/FcnnP/MtcxTwd1t05kk1ot/01j5hb3QrXbSMKM4tbbJEpo4IXn/sc7Mjo7tOXWbz1Sw0XU5WxGZ8r213R2fjB3QKcj2rq17xhSPFQSjjNtWL5N5JCRPqB/5QBF22SQw4QHr3b/EMRTYyNdnLUiQL12baG/VIQS8o1U3dGLTN2lFjbkEz+/9SBiTmL7VwIknboSlTaXjCM3s5/qc5T5sLRX2Ol7w00j29aTcdbc4PlPPr1x5grSC4bixycHdDJX/FYgWXcMuba9UyeYNO2qvGdnLUVkyXFmLV5y7j2jM4yulsIFRoW3Gw/UOm/eEK2J/Ab6wT1CWI7cPE5CLcF1Y7qjXVaDXnX/E=
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
branches:
  only:
  - master
  - test
  - dev
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar